#!/bin/sh

# v2025-12-21
ENABLED=yes
PROCS="/opt/bin/amneziawg-go"
PATH="/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
DESC="AmneziaWG OpkgTun"
PROGRAM="${0##*/}"
AWG_BIN="/opt/bin/awg"

# Настройки для пользователей
OPKGTUN_INTERFACE="opkgtun0"
AWG_CONF="/opt/etc/amnezia/amneziawg/awg0-opkgtun0.conf"
# Конец настроек для пользователей


cmd_start() {
    [ "$ENABLED" != "yes" ] && die "⚠️ Service is disabled in script (ENABLED=no)."
    [ -x "$PROCS" ] || die "⚠️ Application \e[3m $PROCS \e[0m not found or not executable."
    [ -x "$AWG_BIN" ] || die "⚠️ Application \e[3m $AWG_BIN \e[0m not found or not executable."
    [ -f "$AWG_CONF" ] || die "⚠️ AWG config-file \e[3m $AWG_CONF \e[0m does not exist!"

    if pgrep -f "$PROCS $OPKGTUN_INTERFACE" > /dev/null; then
        log "ℹ️ AmneziaWG for \e[3m$OPKGTUN_INTERFACE\e[0m already running!"
        log "ℹ️ Use \"\e[3m$PROGRAM restart\e[0m\" if you need restart this interface." && echo "" && return 0
    fi

    log "ℹ️ Starting AmneziaWG \e[3m$OPKGTUN_INTERFACE\e[0m interface..."
    logger -t "[Entware AWG-Go][Info]" "Starting AWG for $OPKGTUN_INTERFACE interface..."
    "$PROCS" "$OPKGTUN_INTERFACE" >/dev/null 2>&1 &

    local retries=10
    while [ ! -d "/sys/class/net/$OPKGTUN_INTERFACE" ] && [ $retries -gt 0 ]; do
        sleep 1 && retries=$((retries - 1))
    done
    sleep 2
    if [ -d "/sys/class/net/$OPKGTUN_INTERFACE" ]; then
        if ip link set dev "$OPKGTUN_INTERFACE" up; then
            if ("$AWG_BIN" setconf "$OPKGTUN_INTERFACE" "$AWG_CONF") ; then
                logger -t "[Entware AWG-Go][Info]" "Successfully configured $OPKGTUN_INTERFACE with \"$AWG_CONF\""
                log "✅ Successfully configured AWG-opkgtun: \e[3m$OPKGTUN_INTERFACE\e[0m"
                sleep 2 && echo ""&& cmd_status
            else
                sleep 2 && cmd_stop
                logger -t "[Entware AWG-Go][Err]" "Failed to apply config \"$AWG_CONF\" to $OPKGTUN_INTERFACE!"
                die "❌ Failed to apply config \e[3m$AWG_CONF\e[0m to \e[3m$OPKGTUN_INTERFACE\e[0m."
            fi
        else
            cmd_stop
            logger -t "[Entware AWG-Go][Err]" "Failed to UP network interface $OPKGTUN_INTERFACE!"
            die "❌ Failed to UP network interface \e[3m$OPKGTUN_INTERFACE\e[0m."
        fi
    else
        logger -t "[Entware AWG-Go][Err]" "Interface $OPKGTUN_INTERFACE did not appear after start!"
        die "❌ Interface \e[3m$OPKGTUN_INTERFACE\e[0m did not appear after start."
    fi
}

cmd_stop() {
    [ -x "$PROCS" ] || die "⚠️ Application \e[3m $PROCS \e[0m not found or not executable."

    local AWG_PID=$(pgrep -f "$PROCS $OPKGTUN_INTERFACE")
    if [ -n "$AWG_PID" ]; then
        logger -t "[Entware AWG-Go][Info]" "Stopping  AWG for $OPKGTUN_INTERFACE with \"$AWG_CONF\"..."
        log "ℹ️ Stopping AmneziaWG for \e[3m$OPKGTUN_INTERFACE\e[0m (PID: $AWG_PID)..."
        kill "$AWG_PID" > /dev/null 2>&1

        local timeout=5
        while pgrep -f "$PROCS $OPKGTUN_INTERFACE" > /dev/null && [ $timeout -gt 0 ]; do
            sleep 1 && timeout=$((timeout - 1))
        done

        if pgrep -f "$PROCS $OPKGTUN_INTERFACE" > /dev/null; then
            logger -t "[Entware AWG-Go][Warn]" "Process did not respond, forcing termination AWG for $OPKGTUN_INTERFACE..."
            log "⚠️ Process did not respond, forcing termination... ⚠️"
            kill -9 "$AWG_PID" > /dev/null 2>&1
        fi

        if [ -d "/sys/class/net/$OPKGTUN_INTERFACE" ]; then
             ip link set dev "$OPKGTUN_INTERFACE" down
        fi
        logger -t "[Entware AWG-Go][Info]" "AWG for $OPKGTUN_INTERFACE with \"$AWG_CONF\" stopped successfully."
        log "✅ AmneziaWG for \e[3m$OPKGTUN_INTERFACE\e[0m stopped successfully."
    else
        log "ℹ️ AmneziaWG for \e[3m$OPKGTUN_INTERFACE\e[0m is NOT running."
    fi
}

cmd_status() {
    [ -x "$PROCS" ] || die "⚠️ Application \e[3m $PROCS \e[0m not found or not executable."
    [ -x "$AWG_BIN" ] || die "⚠️ Application \e[3m $AWG_BIN \e[0m not found or not executable."

    echo -e "==================== INTERFACE \e[3m$OPKGTUN_INTERFACE\e[0m STATUS ===================="
    if [ ! -d "/sys/class/net/$OPKGTUN_INTERFACE" ]; then
        echo -e "❌ Interface \e[3m$OPKGTUN_INTERFACE\e[0m does NOT exist!"
    else
        ip -c -br link show dev "$OPKGTUN_INTERFACE"
        
        if pgrep -f "$PROCS $OPKGTUN_INTERFACE" > /dev/null; then
            logger -t "[Entware AWG-Go][Info]" "AWG-Go for $OPKGTUN_INTERFACE with \"$AWG_CONF\" running"
            log "✅ AWG-Go for \e[3m$OPKGTUN_INTERFACE\e[0m running"
            local RAW_LASTHANDSHAKE=$("$AWG_BIN" show "$OPKGTUN_INTERFACE" latest-handshakes 2>/dev/null)
            LASTHANDSHAKE=$(echo "$RAW_LASTHANDSHAKE" | awk '{print $2}' 2>/dev/null)
            if [ -n "$LASTHANDSHAKE" ] && [ "$LASTHANDSHAKE" -ne 0 ] 2>/dev/null; then
                logger -t "[Entware AWG-Go][Info]" "$OPKGTUN_INTERFACE with \"$AWG_CONF\" Last Handshake: $(date -d "@$LASTHANDSHAKE" '+%Y-%m-%d %H:%M:%S')"
                log "ℹ️ Last Handshake: $(date -d "@$LASTHANDSHAKE" '+%Y-%m-%d %H:%M:%S')"
            else
                logger -t "[Entware AWG-Go][Warn]" "$OPKGTUN_INTERFACE with \"$AWG_CONF\" Last Handshake: NONE (No connection)"
                log "⚠️ Last Handshake: ❌ \e[31mNONE\e[0m (No connection)"
            fi

            echo "-------------------------------------------------------------------"
            log "ℹ️ Testing external IP via \e[3m$OPKGTUN_INTERFACE\e[0m..."
            local VPS_IP=$(curl --interface "$OPKGTUN_INTERFACE" -s --max-time 3 ifconfig.me 2>/dev/null)
            if [ -n "$VPS_IP" ]; then
                logger -t "[Entware AWG-Go][Info]" "External IP via $OPKGTUN_INTERFACE: $VPS_IP"
                log "✅ External IP via \e[3m$OPKGTUN_INTERFACE\e[0m: \e[33m$VPS_IP\e[0m"
            else
                logger -t "[Entware AWG-Go][Warn]" "Failed to obtain external IP via $OPKGTUN_INTERFACE"
                log "❌ \e[31mFailed to obtain external IP\e[0m via \e[3m$OPKGTUN_INTERFACE\e[0m"
            fi
        else
            log "ℹ️ AmneziaWG for \e[3m$OPKGTUN_INTERFACE\e[0m NOT running!"
        fi
    fi
    echo "===================================================================" && echo ""
}



log() {
    echo -e "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
}


die() {
    log "ERROR: $*" >&2
    exit 1
}


case "$1" in
    start)   cmd_start ;;
    stop)    cmd_stop ;;
    restart) cmd_stop; sleep 1; cmd_start ;;
    status)  cmd_status ;;
    *)       echo "Usage: $0 {start|stop|restart|status}"; exit 1 ;;
esac
